# version: "3.8"

services:
  db:
    restart: always
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthworm
    volumes:
      - data:/var/lib/postgres/main-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - data:/var/lib/redis
    ports:
      - 6379:6379
  web:
    build:
      context: ./apps/client
      args:
        NUXT_API_BASE: http://192.168.0.11:1231/
        NUXT_LOGTO_APP_ID: s464nkka8vr7roobvk9r3
        NUXT_LOGTO_ENDPOINT: http://192.168.0.11:3010/
        NUXT_BACKEND_ENDPOINT: http://192.168.0.11:1231/
        NUXT_LOGTO_SIGN_IN_REDIRECT_URI: http://192.168.0.11:1230/callback
        NUXT_LOGTO_SIGN_OUT_REDIRECT_URI: http://192.168.0.11:1230/
        NUXT_HELP_DOCS_URL: https://earthworm-docs.cuixueshe.com/get-started/
    image: earthworm_web:latest
    restart: always
    ports:
      - 1230:3000
    environment:
      NUXT_API_BASE: http://192.168.0.11:1231/
      NUXT_LOGTO_APP_ID: s464nkka8vr7roobvk9r3
      NUXT_LOGTO_ENDPOINT: http://192.168.0.11:3010/
      NUXT_BACKEND_ENDPOINT: http://192.168.0.11:1231/
      NUXT_LOGTO_SIGN_IN_REDIRECT_URI: http://192.168.0.11:1230/callback
      NUXT_LOGTO_SIGN_OUT_REDIRECT_URI: http://192.168.0.11:1230/
      NUXT_HELP_DOCS_URL: https://earthworm-docs.cuixueshe.com/get-started/
  api_server:
    build:
      context: ./
    image: earthworm_api:latest
    restart: always
    ports:
      - 1231:3001
    environment:
      DATABASE_URL: postgres://postgres:password@192.168.0.11:5433/earthworm
      SECRET: sjldk92#sd903mnc./xklsjdf9sdfj
      REDIS_URL: redis://192.168.0.11:6379
      LOGTO_CLIENT_ID: 1ummxzdeoyxhquvf14z4m
      LOGTO_CLIENT_SECRET: rja2w7B2UXaOfu6tEW9fZHn6kNQMRjpC
      LOGTO_M2M_API: https://default.logto.app/api
      LOGTO_ENDPOINT: http://192.168.0.11:3010/
      BACKEND_ENDPOINT: http://192.168.0.11:1231/

  logto:
    restart: always
    depends_on:
      logtoPostgres:
        condition: service_healthy
    image: svhd/logto:1.18.0
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3010:3010
      - 3011:3011
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@logtoPostgres:5432/logto
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - PORT=3010
      - ADMIN_PORT=3011
      - ENDPOINT
      - ADMIN_ENDPOINT
  logtoPostgres:
    restart: always
    image: postgres:14-alpine
    user: root
    volumes:
      - "./.volumes/logto_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
    driver: local
